export const products = [
    {
      id: 1,
      images: [
        { url: "https://i.imgur.com/SvGyHs1.jpeg", caption: "01-Pretas Artisticas Reto.jpg" },
        { url: "https://i.imgur.com/X1eB5mW.jpeg", caption: "01.1 - Pretas Wig e Implosion.jpg" },
      ],
      title: "Piteira Black Arts",
      techniques: "Wig-Wag(reverse), Implosion",
      bodyColor: "Corpo preto",
      thickness: "Espessura: 6 mm",
      price: 100,
      oldPrice: 120,
    },
    {
      id: 2,
      images: [
        { url: "https://i.imgur.com/Fq4jG2I.jpeg", caption: "03 - Artisticas Verdes Reto.jpg" },
        { url: "https://i.imgur.com/UWSwWUI.jpeg", caption: "03.1 - Artisticas Verde Varias" },
      ],
      title: "Piteira Green Arts",
      techniques: "Variações Artísticas",
      bodyColor: "Corpo verde translúcido",
      thickness: "Espessura: 5,5 mm",
      price: 90,
      oldPrice: 110,
    },
    {
      id: 3,
      images: [
        { url: "https://i.imgur.com/DGXgF1b.jpeg", caption: "05 - Donuts Wig-Wag e Reverse Reto" },
        { url: "https://i.imgur.com/QkWgoHr.jpeg", caption: "05.1 - Donuts Wig Varios" },
      ],
      title: "Piteira Donuts Wig-Wag",
      techniques: "Wig-Wag, Reverse-Wag",
      bodyColor: "Corpo personalizado: Donuts",
      thickness: "Espessuras e tamanhos variados",
      price: 80,
      oldPrice: 100,
    },
    {
      id: 4,
      images: [
        { url: "https://i.imgur.com/2JIHNOy.jpeg", caption: "06 - Implosion Snake Reta" },
        { url: "https://i.imgur.com/yiMyIJP.jpeg", caption: "06.1 - Implosion Snake Varias" },
      ],
      title: "Piteira Implosion Style",
      techniques: "Implosion",
      bodyColor: "Corpo personalizado",
      thickness: "Espessuras e tamanhos variados",
      price: 70,
      oldPrice: 90,
    },
    {
      id: 5,
      images: [
        { url: "https://i.imgur.com/AY6jv2F.jpeg", caption: "07 - Wig-Wag e Reverse Snake" },
        { url: "https://i.imgur.com/T6N7CMC.jpeg", caption: "07.1 - Wig-Wag Snake Varios" },
      ],
      title: "Piteira Wig-Wag",
      techniques: "Wig-Wag ou Reverse-Wag",
      bodyColor: "Corpo personalizado",
      thickness: "Espessuras e tamanhos variados",
      price: 65,
      oldPrice: 85,
    },
    {
      id: 6,
      images: [
        { url: "https://i.imgur.com/moYJIjx.jpeg", caption: "08 - Waves Snake Reto" },
        { url: "https://i.imgur.com/viT6Yt5.jpeg", caption: "08.1 - Waves Snake varias" },
      ],
      title: "Piteira Waves Style",
      techniques: "Waves",
      bodyColor: "Corpo personalizado",
      thickness: "Espessuras e tamanhos variados",
      price: 60,
      oldPrice: 80,
    },
    {
      id: 7,
      images: [
        { url: "https://i.imgur.com/cO6bVCh.jpeg", caption: "09 - Zanfirico Snake Reto" },
        { url: "https://i.imgur.com/lItHlUi.jpeg", caption: "09.1 - Zanfirico Snake Varias" },
      ],
      title: "Piteira Zanfírico Style",
      techniques: "Zanfírico",
      bodyColor: "Corpo personalizado",
      thickness: "Espessuras e tamanhos variados",
      price: 50,
      oldPrice: 70,
    },
    {
      id: 8,
      images: [
        { url: "https://i.imgur.com/ptuxUj6.jpeg", caption: "Chopp Preto Reto" },
      ],
      title: "Piteira Chopp",
      techniques: "Sculpture – Escultura",
      bodyColor: "Corpo preto e verde translúcido",
      thickness: "Espessura: 5,5 mm",
      colors: "Cores: Canary e Star White",
      price: 120,
      oldPrice: 140,
    },
    {
      id: 9,
      images: [
        { url: "https://i.imgur.com/duhamZq.jpeg", caption: "Pretas Waves retas" },
      ],
      title: "Piteira Black Waves",
      techniques: "Waves",
      bodyColor: "Corpo preto",
      thickness: "Espessura: 6 mm",
      price: 90,
      oldPrice: 110,
    },
  ];
  